In [1]:
import tensorflow as tf

2023-12-17 01:17:07.205599: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-17 01:17:07.345415: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-17 01:17:07.345481: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-17 01:17:07.349828: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-17 01:17:07.369115: I tensorflow/core/platform/cpu_feature_guar

In [2]:
tf.constant(10)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [10]:
changable_var = tf.Variable([10,7])
changable_var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [11]:
changable_var[0].assign(15)
changable_var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([15,  7], dtype=int32)>

In [12]:
import torch
var = torch.Tensor([10,11])
var

tensor([10., 11.])

In [13]:
var[0] = 1
var

tensor([ 1., 11.])